name: tdlib_print_thermal
description: Plugin for CTCD
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.5.0 <3.0.0"
  flutter: ">=0.10.15 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: id.ctcorp.tdlib_print_thermal
    pluginClass: TdlibPrintThermalPlugin
